### ISSUE TITLE
Retire cleardata/forseti-policy-enforcer Docker Hub container

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/real-time-enforcer#10]
After two releases where Forseti deployment is using the new [forsetisecurity/real-time-enforcer ](https://hub.docker.com/r/forsetisecurity/real-time-enforcer) we should retire the [cleardata/forseti-policy-enforcer](https://hub.docker.com/r/cleardata/forseti-policy-enforcer) container.

Issue #9 needs to be completed before we take any action on this issue..

**Comment by kevensen** [comment]
Are there further AI's that need to be completed?  Or can this be closed?

**Comment by rvandegrift** [comment]
looks good to me - thanks for the nudge!
