### ISSUE TITLE
CloudSQL databases created via the gcloud command line tool are not evaluated or remediated

### ISSUE THREAD

**Issue by jceresini** [forseti-security/real-time-enforcer#14]
AuditLogs for CloudSQL instances created with the gcloud command line tool seem to come through with a resource.labels.database_id that is blank. Since the stackdriver log parser is unable to pull out the details needed to identify the resource, remediation fails.

**Comment by jceresini** [comment]
This appears to affect any instances created with the API. I was able to replicate using the API explorer. So it seems only the cloud console creates proper audit logs

**Comment by rvandegrift** [comment]
For later reference: https://issuetracker.google.com/issues/137629452

**Comment by jceresini** [comment]
Resolved by #15
