### ISSUE TITLE
Create & configure automated container release process

### ISSUE THREAD

**Issue by rvandegrift** [forseti-security/real-time-enforcer#3]
After transferring the repo into forseti-security, Docker Hub will no longer allow me to configure autobuilds.  This will prevent releases, so we should figure out what to do moving forward.

**Comment by dekuhn** [comment]
Do you think this is a docker hub re-configuration or are there changes you think we also need to modify on the github repository?

**Comment by rvandegrift** [comment]
It's not a simple config change - I don't have permission to configure builds for the forseti-security organizations, I think because I'm not a member.  So if the plan is to continue releasing on Docker Hub, I think a forseti-security member will need to create a new Docker Hub organization.

**Comment by dekuhn** [comment]
Ok, let me look into this with the team. Most are at Next'19 this week so it might not be until next week until we can resolve this.

**Comment by dekuhn** [comment]
In discussions at Forseti Day last week the feedback about where to store this long-term was to keep hosting the container in Docker hub, but mirror it to Google Container Registry.

**Comment by dekuhn** [comment]
We have DockerHub complete and 2.17 is the first release with the update TF setting. 

After 2 releases we agreed to turn down the old ClearData Docker Hub container. Keeping this bug open for tracking that final task/

**Comment by dekuhn** [comment]
Just saw we have issue #9 tracking this so closing this issue.
